export const LANG_EN = {
  'login.welcome-message': 'Welcome! Please login with your GitHub account to searh for city weathers',
  'login.login-button.text': 'Login',
  'login.logout-button.text': 'Logout',
  'general.error-message': 'An error occurred. Please try again later.',
  'please-wait': 'Please wait...',
  'weather.city-input.label': 'City',
  'weather.get-weather-button.text': 'Get Weather',
  'weather.greeting': 'Hello, {name}!',
  'weather.weather-details.city-unkown': '{city} City not found.',
  'weather.weather-details.table-header.city': 'City',
  'weather.weather-details.table-header.temperature': 'Temperature',
  'weather.weather-details.table-header.humidity': 'Humidity',
  'weather.weather-details.table-header.wind-speed': 'Wind Speed',
}