export const LANG_EN = {
  'login.app-name': 'City Weather App',
  'login.welcome-message': 'A City weather app that requires a Github account? \nSay no more! Login to get started.',
  'login.login-button.text': 'Login',
  'login.logout-button.text': 'Logout',
  'general.error-message': 'An error occurred. Please try again later.',
  'please-wait': 'Please wait...',
  'weather.city-input.label': 'City',
  'weather.get-weather-button.text': 'Get Weather',
  'weather.greeting': 'Hello, {name}!',
  'weather.weather-details.city-unkown': '{city} City not found.',
  'weather.weather-details.table-header.date': 'Date',
  'weather.weather-details.table-header.temperature': 'Temperature (F)',
  'weather.weather-details.table-header.feels-like': 'Feels like (F)',
  'weather.weather-details.table-header.humidity': 'Humidity',
  'weather.weather-details.table-header.description': 'Description',
  'weather.weather-details.table-header.main': 'Main',
  'weather.weather-details.table-header.wind-speed': 'Wind Speed',
  'weather.weather-details.back-button.text': 'Search Another',
  'weather.weather-details.error-message': 'An error occurred. Please try again later.',
}